### PR TITLE
30 Altmetric Badge Bug Redux

### LINKED ISSUE #30: Altmetrics Badge bug
The side "tab" and section title disappears after the loading is completely finished. The badge does stick around though.

### PR DESCRIPTION
**Pull request by Meowcenary**
Fixing bug where two altmetrics badges will render if both the doi and pubmed id are present. closes #30

### CODE REVIEW

File: primo-explore/custom/main.js [hunk 1]
```diff
@@ -556,10 +556,8 @@ app.controller('FullViewAfterController', ['angularLoad', '$http', '$scope', '$e
           return;
         });
       }, 3000);
-    }
-
-    // pubmed lookup. copies above code, but replaces doi with pmid
-    if (vm.pmid) {
+    } // pubmed lookup. copies above code, but replaces doi with pmid
+    else if (vm.pmid) {
```
Comment (sharpattack) [inline primo-explore/custom/main.js:560]: 👍

**Review by sharpattack — APPROVED** [review]

**Review by jpastva — APPROVED** [review]
Else if for the win! I think this takes care of this issue.
